### ISSUE TITLE
FTBFS with glibc 2.43 due to ISO C23 const return types

### ISSUE THREAD

**Issue by babelouest** [zmartzone/liboauth2#70]
Hello,

This bug is also forwarded from Debian bug [#1126815](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1126815)

liboauth2 fails to build with glibc 2.43 due to new return type on `strstr` function.

```
| libtool: compile:  gcc -DPACKAGE_NAME=\"liboauth2\" -DPACKAGE_TARNAME=\"liboauth2\" -DPACKAGE_VERSION=\"2.2.0\" "-DPACKAGE_STRING=\"liboauth2 2.2.0\"" -DPACKAGE_BUGREPORT=\"hans.zandbelt@openidc.com\" -DPACKAGE_URL=\"\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -Wall -Werror -Wno-error=deprecated-declarations -I./include -I./src -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr/include/x86_64-linux-gnu -isystem /usr/include/mit-krb5 -isystem /usr/include/mit-krb5 -I/usr/include/p11-kit-1 -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/build/reproducible-path/liboauth2-2.2.0=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -c src/jose.c  -fPIC -DPIC -o src/.libs/liboauth2_la-jose.o
| src/jose.c: In function 'oauth2_jose_jwt_header_peek':
| src/jose.c:1003:11: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
|  1003 |         p = strstr(compact_encoded_jwt, ".");
|       |           ^
| cc1: all warnings being treated as errors
| make[1]: *** [Makefile:1387: src/liboauth2_la-jose.lo] Error 1
| make[1]: Leaving directory '/build/reproducible-path/liboauth2-2.2.0'
| dh_auto_build: error: make -j1 returned exit code 2
| make: *** [debian/rules:13: binary] Error 25
| dpkg-buildpackage: error: debian/rules binary subprocess failed with exit status 2
```

This is not urgent as glibc 2.43 is not in testing for now, just in experimental.

**Comment by zandbelt** [comment]
thanks! fixed in https://github.com/OpenIDC/liboauth2/commit/155b93b2efd1e8b0022c9bdad2297a2a670dc29c

**Comment by zandbelt** [comment]
https://github.com/OpenIDC/liboauth2/releases/tag/v2.2.1
